services:
  vcptoolbox:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: vcptoolbox-prod
    ports:
      - "6005:6005"    # VCP主服务端口
      - "5890:5890"    # WebSocket端口
    environment:
      - TZ=Asia/Shanghai
      - NODE_ENV=production
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
    entrypoint: >
      sh -c "
        apk add --no-cache chromium &&
        echo 'Chromium installed:' && chromium --version &&
        node server.js
      "
    volumes:
      # 全挂载方式 - 将整个项目目录挂载到容器中
      - .:/usr/src/app

      # 保持 node_modules 和 pydeps 独立于容器，避免本地环境覆盖容器内的依赖
      - /usr/src/app/node_modules
      - /usr/src/app/pydeps
    
    restart: unless-stopped
    
    # 健康检查
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:6005/"] 
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

# 使用全挂载方式，不需要单独的数据卷定义

# 网络配置
networks:
  default:
    name: vcptoolbox-network
